### ISSUE TITLE
property name not found

### ISSUE THREAD

**Issue by mockiemockiz** [rdohms/dms-filter-bundle#22]
I got this error:
![screenshot from 2014-11-25 08 15 45](https://cloud.githubusercontent.com/assets/1708946/5176416/64838e68-747b-11e4-8a61-5b1b5f28f88f.png)

`property name not found` I think this error means property name for category entity but I'm not sure about this error. and I can't search it in google because the error too general to be keyword.

This is happen :
- only when update (not in create)
- This is happen when I create new post that has relation to category entity.
- this form using entity choice for category_id from category entity.

this my type form class:

```
            ->add('categoryId', 'entity', [
                'class' => $this->parameters['category_entity_name'], // MockizartBlogBundle:MockblogCategory
                'property' => 'name',
                'empty_value' => 'No parent',
                'required' => false
            ])
            ->add('title')
```

this is notation from category entity:

```
 /**
     * @Filter\StripTags()
     * @Filter\Trim()
     * @Filter\StripNewlines()
     *
     * @var string
     */
    private $name;

```

and this is from my post entity class:

```

    /**
     * Set categoryId
     *
     * @param MockblogCategory $category
     * @internal param int|\Mockizart\Bundle\BlogBundle\Entity\MockblogCategory $categoryId
     * @return MockblogPost
     */
    public function setCategoryId(MockblogCategory $category)
    {
        $this->categoryId = $category;

        return $this;
    }

    /**
     * Get categoryId
     *
     * @return integer 
     */
    public function getCategoryId()
    {
        return $this->categoryId;
    }
```

my post entity mapping file:

```
    manyToOne:
        userId:
            targetEntity: Mockizart\Bundle\BlogBundle\Entity\User
            joinColumn:
              name: user_id
              referencedColumnName: id
            type: integer
            nullable: false
            unsigned: false
        categoryId:
            targetEntity: Mockizart\Bundle\BlogBundle\Entity\MockblogCategory
            joinColumn:
              name: category_id
              referencedColumnName: id
            type: integer
            nullable: false
            unsigned: false
            comment: ''
```

Thanks.
